### ISSUE TITLE
GitHub release assets added from `build/*.zip` inconvenient

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/deployer#14]
https://github.com/pronamic/wp-deployer/blob/10ed16a60f9b5c2b456a818538ac12f79d125e5f/src/VersionCommand.php#L581-L598

Added in https://github.com/pronamic/wp-deployer/commit/177c421046d057d7429e7287783b545c97727e79 by @rvdsteege. We don't know if users have a `build` folder and the `*.zip` are up to date. In the release of a plugin an old ZIP file was attached to the release since i didn't have a build script in place.

https://github.com/pronamic/wp-pronamic-pay/blob/ddb3cc968144f9619d5d6121e4c90b821967f8d2/composer.json#L121-L123

**Comment by rvdsteege** [comment]
> GitHub release assets added from build/*.zip inconvenient

The opposite is also inconvenient — manually having to upload the release asset. I was surprised the asset was 'missing' from the GitHub release when I made the change.

We could maybe only include files that are created in the last X minutes (if the `build` directory exists)?

**Comment by remcotolsma** [comment]
I have asked https://chat.openai.com/ about this:

> Should `npm version` also create a GitHub release?

---

> Whether or not `npm version` should also create a GitHub release would depend on the specific needs and preferences of the project and its development team.
> 
> Creating a GitHub release alongside a new version of an npm package can be useful for providing users with a clear changelog and a well-defined release point, as well as allowing for easy distribution of the new version through GitHub's release assets feature.
> 
> However, creating a GitHub release may not always be necessary or desired, particularly for smaller or more internal projects where the benefits may not outweigh the added complexity. Additionally, some projects may prefer to handle release management entirely within the context of their npm package, rather than creating a separate release on GitHub.
> 
> Ultimately, the decision of whether or not to create a GitHub release alongside an npm package version should be based on the specific needs and goals of the project and its development team, and may vary from project to project.

Since it it may vary from project to project i don't the `gh release create` belongs in the `wp-deployer version` command. I marked this as depreacted for now in https://github.com/pronamic/wp-deployer/commit/099bbf152e4bd7c67c0e6a5396a6c95f49806c71.
