### ISSUE TITLE
Run `composer run-script version` if available

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/deployer#5]
Check `composer.json` `scripts` property for `version` script and run if defined.

- `preversion`
- `version`
- `postversion`

> 2. Run the `preversion` script. These scripts have access to the old `version` in package.json. A typical use would be running your full test suite before deploying. Any files you want added to the commit should be explicitly added using `git add`.

> 4. Run the `version` script. These scripts have access to the new `version` in package.json (so they can incorporate it into file headers in generated files for example). Again, scripts should explicitly add generated files to the commit using `git add`.

> 6. Run the `postversion` script. Use it to clean up the file system or automatically push the commit and/or tag.

- https://docs.npmjs.com/cli/v8/commands/npm-version
- https://www.npmjs.com/package/@npmcli/run-script
- https://github.com/composer/composer/issues/8304

**Comment by rvdsteege** [comment]
Seems this has been implemented already:

https://github.com/pronamic/wp-deployer/blob/177c421046d057d7429e7287783b545c97727e79/src/VersionCommand.php#L122-L127

https://github.com/pronamic/wp-deployer/blob/177c421046d057d7429e7287783b545c97727e79/src/VersionCommand.php#L503-L508

https://github.com/pronamic/wp-deployer/blob/177c421046d057d7429e7287783b545c97727e79/src/VersionCommand.php#L590-L595
