### ISSUE TITLE
Renamed and removed tags are pushed

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/deployer#7]
Colleagues who still have old tags locally will push them automatically?

https://github.com/pronamic/wp-deployer/blob/778fa74c200fd5d9d6d34dabd2b83af593ddbd29/src/VersionCommand.php#LL566C35-L566C50

See for example:
https://github.com/pronamic/wp-pronamic-pay-gravityforms/tags

CC @rvdsteege

**Comment by remcotolsma** [comment]
Change command to push just the specific tag?

```
git push origin refs/tags/tag_a
```

https://stackoverflow.com/questions/23212452/how-to-only-push-a-specific-tag-to-remote

**Comment by rvdsteege** [comment]
I also use ` git fetch --prune --prune-tags origin` to remove local tags that don't exist on remote anymore, followed by `git fetch --all -tags`.

**Comment by remcotolsma** [comment]
Improved in https://github.com/pronamic/wp-deployer/commit/91e96cba5126a87be4707f84fa931ef45e1be9d0.
