### ISSUE TITLE
Display bump version result

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/deployer#9]
https://github.com/pronamic/wp-deployer/blob/778fa74c200fd5d9d6d34dabd2b83af593ddbd29/src/VersionCommand.php#L237-L252

The `choice` function does not allow for labels as far as i know:
https://symfony.com/doc/current/console/style.html#user-input-methods

It would be great if we can display what version the `patch`, `minor` and `major` options will result in.

- https://github.com/thephpleague/climate
- https://github.com/nunomaduro/termwind

**Comment by rvdsteege** [comment]
Looks like you can just provide an associative array. The key is included in the question, but the answer should match the choice value.

From https://github.com/symfony/symfony/issues/40439#issuecomment-812875463:

```
 Choose something:
  [key_0] value_0
  [key_1] value_1
  [key_2] value_2
 > value_1
```

- https://github.com/symfony/symfony/blob/61e6bff1535fdf2c315163cd285f43372b12a05b/src/Symfony/Component/Console/Helper/QuestionHelper.php#L199-L212
- https://github.com/symfony/symfony/blob/9d11f5a19fc3d88daea44475814d54b954cf117b/src/Symfony/Component/Console/Question/ChoiceQuestion.php#L138-L148
